# originally from https://gist.github.com/dan-blanchard/7045057
sudo: false
language: python

python:
  # Note: this is currently ignored because the environment contains an explicit python version
  # also see the later note on this
  - "3.6"

cache:
  apt: true
  directories:
    - $HOME/.local

# Setup anaconda
before_install:
  # Install miniconda
  # This comes from http://conda.pydata.org/docs/travis.html
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

# Install packages
install:
  # NOTE: we're not actually installing this version of Python here due to the environment.
  - conda env create --file environment.yml # python=$TRAVIS_PYTHON_VERSION
  - source activate dynamicscontrol
  - pip install .
  - conda env export  # debugging

# Run tests
script:
  - pytest --verbose test.py
  - pytest tests
