name: dynamicscontrol
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.6
  - matplotlib==3.0.2
  - numpy==1.15.4
  - scipy==1.1.0
  - sympy==1.3
  - control==0.8.0
  - pandas=0.23.4
  - keras=2.2.4
  - scikit-learn==0.20.1
  - pytest==4.0.2
  - jupyter==1.0.0
  - ipython==7.3.0
  - ipywidgets==7.2.1
  - pytest-xdist==1.27.0
  - xlrd==1.2.0
